[project]
name = "apartment-drivers"
version = "0.1.0"
description = ""
authors = [{ name = "Martin Petri Bagger" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.2",
    "scikit-learn>=1.4.2",
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.3",
    "lxml>=5.2.1",
    "selenium>=4.19.0",
    "mlflow>=2.12.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
